# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be860802c0716883c4888d7243481879487a9fc2306f41cd6c75fd820c83a42dc462acf81b80064224c87fa492188db18dd442aac01ed431d7f0eaf43614571

test:
  secret_key_base: f1a204cdb87638e56052c59cbe7126a6ac174e9c1c7665412678d9c2344d9dd41007ac9c187becf93407048cd599a016fd1b1721a19d0dd7cf6866b5ed1b8ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
